### ISSUE TITLE
Adding default `assistants=v1` header to beta endpoints

### ISSUE THREAD

**Issue by huytool157** [openai/openai-openapi#138]
Should the OpenAPI spec add a default parameter header `assistants=v1` to beta endpoints, something like this?

```
/assistants:
  get:
    operationId: listAssistants
    tags:
      - Assistants
    summary: Returns a list of assistants.
    parameters:
      - in: header
        name: assistants
        required: false
        schema:
          type: string
        default: v1
      - name: limit
        in: query
        description: &pagination_limit_param_description |
          A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
        required: false
        schema:
          type: integer
          default: 20
      - name: order
        in: query
        description: &pagination_order_param_description |
          Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
        schema:
          type: string
          default: desc
          enum: ["asc", "desc"]
```
