### ISSUE TITLE
can we classify all apis into more tags

### ISSUE THREAD

**Issue by sarike** [openai/openai-openapi#22]
Currently all apis are in the save tag `OpenAI`.

Can we classify all apis into more tags? e.g:

```yaml
tags:
  - name: Engines
  - name: Models
  - name: Completions
  - name: Edits
  - name: Images
  - name: Files
  - name: Embeddings
  - name: Fine-tunes
  - name: Moderations
  - name: Others
```

Many api tools use tags to render UI with better user experience. Even though they can modify the copied file, but when the yaml file here is updated, the work to merge them is boring.

If this is ok, I am glad to do it.
