### ISSUE TITLE
OpenAPI document missing the security scheme definition

### ISSUE THREAD

**Issue by justinyoo** [openai/openai-openapi#25]
According to the [Authorization section of the API document](https://platform.openai.com/docs/api-reference/authentication), to make an API call it requires one mandatory `Authorization` header and an optional `OpenAI-Organization` header.

As both are missing in the OpenAPI document, they need to be added. Here are examples:

```yaml
...
paths:
  ...
  /models:
    get:
      operationId: listModels
      tags:
        - OpenAI
      summary: Lists the currently available models, and provides basic information about each one such as the owner and availability.
      # add optional header parameter like below
      parameters:
        - in: header
          name: OpenAI-Organization
          required: false
          schema:
            type: string
            example:
              org-hP479gBqdEuqjgkVyFPZ5g5h
          description: For users who belong to multiple organizations, you can pass a header to specify which organization is used for an API request. Usage from these API requests will count against the specified organization's subscription quota.
...
# global authorization
security:
  - api_key: []

components:
  # authorization scheme
  securitySchemes:
    api_key:
      type: 'http'
      scheme: 'bearer'
      bearerFormat: 'Bearer'
...
```
