### ISSUE TITLE
Stop definition default value missing double quotes.

### ISSUE THREAD

**Issue by lhozdroid** [openai/openai-openapi#290]
Line 7226, stop definition, default value missing double quotes, causing issues on generation.

```
        stop:
          description: &completions_stop_description >
            Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
          default: null
          nullable: true
          oneOf:
            - type: string
              default: <|endoftext|>
              example: "\n"
              nullable: true
            - type: array
              minItems: 1
              maxItems: 4
              items:
                type: string
                example: '["\n"]'
```
