### ISSUE TITLE
Integer maximum value is 9223372036854775807, but the value in the document is 9223372036854776000

### ISSUE THREAD

**Issue by atacan** [openai/openai-openapi#360]
```yaml
seed:
  type: integer
  minimum: -9223372036854776000
  maximum: 9223372036854776000
  nullable: true
  description: >
```
