### ISSUE TITLE
bearer/basic identity_edge references not listed under components/securitySchemes

### ISSUE THREAD

**Issue by janodev** [openai/openai-openapi#389]
It appears there are references to `bearer_identity_edge` and `basic_identity_edge` that are not listed under `components/securitySchemes`.

```yaml
paths:
...
  /organization/admin_api_keys:
...

components:
  schemas:
...
  securitySchemes:
    ApiKeyAuth: <------ EXISTING
      type: http
      scheme: bearer
    bearer_identity_edge: <------ MISSING
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer authentication using identity edge token
    basic_identity_edge: <------ MISSING
      type: http
      scheme: basic
      description: Basic authentication using identity edge credentials
```

so for openapi.yaml d2eaa35

```patch
--- openapi.current.yaml	2025-01-09 03:47:59
+++ openapi.patched.yaml	2025-01-09 04:05:48
@@ -25661,8 +25661,17 @@
           }
   securitySchemes:
     ApiKeyAuth:
+      type: http
+      scheme: bearer
+    bearer_identity_edge:
       type: http
       scheme: bearer
+      bearerFormat: JWT
+      description: Bearer authentication using identity edge token
+    basic_identity_edge:
+      type: http
+      scheme: basic
+      description: Basic authentication using identity edge credentials
 security:
   - ApiKeyAuth: []
 x-oaiMeta:
```
