### ISSUE TITLE
License URL in spec should point to the raw text

### ISSUE THREAD

**Issue by dolmen** [openai/openai-openapi#417]
From the [spec](https://github.com/openai/openai-openapi/blob/acea67a5045a6873c6eb2573a6be0e0a7b092ec6/openapi.yaml#L13):
```yaml
  license:
    name: MIT
    url: https://github.com/openai/openai-openapi/blob/master/LICENSE
```

The URL points to the GitHub rendering of the licence. Instead it should point to the raw license content: https://raw.githubusercontent.com/openai/openai-openapi/refs/heads/master/LICENSE
