### ISSUE TITLE
Incorrect `required` Property in `UsageCodeInterpreterSessionsResult`

### ISSUE THREAD

**Issue by philippzagar** [openai/openai-openapi#421]
The OpenAPI specification defines the following type:

```yaml
UsageCodeInterpreterSessionsResult:
  type: object
  description: The aggregated code interpreter sessions usage details of the specific time bucket.
  properties:
    object:
      type: string
      enum:
        - organization.usage.code_interpreter_sessions.result
      x-stainless-const: true
    num_sessions:
      type: integer
      description: The number of code interpreter sessions.
    # ...
  required:
    - object
    - sessions     # doesn't exist!
```

However, the required `sessions` property does not exist in `UsageCodeInterpreterSessionsResult`. The only relevant property appears to be `num_sessions`, so it seems likely that this was an oversight.

### Expected Behavior

The required section should reference `num_sessions` instead of `sessions` to align with the actual properties defined in `UsageCodeInterpreterSessionsResult`:

```yaml
required:
  - object
  - num_sessions
```
