### ISSUE TITLE
Model properties that are both string and enum breaks csharp client generation

### ISSUE THREAD

**Issue by bobend** [openai/openai-openapi#56]
Fx: 

```yaml 
        model:
          description: ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
          type: string
          example: "text-davinci-edit-001"
          anyOf:
            - type: string
            - type: string
              enum: ["text-davinci-edit-001","code-davinci-edit-001"]
```
This example also have an additional `type: string` and breaks [RicoSuter/NSwag](https://github.com/RicoSuter/NSwag)

Could it be changed to:
```yaml 
        model:
          description: ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
          example: "text-davinci-edit-001"
          type: string
          enum: ["text-davinci-edit-001","code-davinci-edit-001"]
```
without breaking compatibles with other language client generators?
